/**
 * Elemental Relationships (Elemental Interactions)
 * 
 * Defines the 5 basic relationships between elements in Wu Xing:
 * - 克 (Overcomes/Conquers): A destroys B
 * - 生 (Generates/Produces): A creates B  
 * - 比 (Comparison/Ally): A same as B
 * - 制 (Controls): B controls A
 * - 化 (Transforms): A+B combines into C
 * 
 * Used to determine Ten Gods (Shi Shen) by analyzing day master Gan
 * against other three Gans (year, month, hour)
 */

import { WuXing } from './types';

export type ElementalRelationship = '克' | '生' | '比' | '制' | '化' | '被生';

// Five Elements cycle: 木 → 火 → 土 → 金 → 水 → 木
const WU_XING_SEQUENCE: WuXing[] = ['木', '火', '土', '金', '水'];

/**
 * Gets the elemental relationship between two elements
 * @param source The acting element
 * @param target The receiving element
 * @returns The relationship type
 */
export function getElementalRelationship(source: WuXing, target: WuXing): ElementalRelationship {
  if (source === target) return '比'; // Same element
  
  const sourceIndex = WU_XING_SEQUENCE.indexOf(source);
  const targetIndex = WU_XING_SEQUENCE.indexOf(target);
  
  if (sourceIndex === -1 || targetIndex === -1) return '比'; // Unknown, default to comparison
  
  const diff = (targetIndex - sourceIndex + 5) % 5;
  
  switch (diff) {
    case 1: return '生'; // Source generates target (next in cycle)
    case 2: return '克'; // Source conquers target (skip one)
    case 3: return '制'; // Source is controlled by target (skip back one)
    case 4: return '被生'; // Source is generated by target (previous in cycle)
    default: return '比';
  }
}

/**
 * Maps elemental relationship to Ten Gods
 * 
 * Standard mapping for Yang (odd) stems (甲,丙,戊,庚,壬):
 * - 比肩 (Robberies): Same Gan
 * - 劫财 (Competitors): Same element, opposite polarity
 * - 食神 (Eating God): Element generated by self
 * - 伤官 (Hurting Officer): Element that self overcomes
 * - 正财 (Direct Wealth): Element that overcomes self (conquered by)
 * - 偏财 (Indirect Wealth): Same as 正财, different timing
 * - 正官 (Direct Officer): Element that conquers self (overcomes)
 * - 七杀 (Seven Killings): Same as 正官, more aggressive
 * - 正印 (Direct Seal): Element that self is generated by
 * - 偏印 (Indirect Seal): Same as 正印, different timing
 * 
 * For Yin (even) stems (乙,丁,己,辛,癸): relationships are reversed/shifted
 */
export function mapRelationshipToShiShen(
  dayGan: string,
  comparisonGan: string,
  isYangDay: boolean
): string {
  // This is a simplified mapping - full implementation would need:
  // 1. Lookup table for all 10 stems
  // 2. Consideration of month position (year/month/day/hour)
  // 3. Gender-based logic
  
  const ganYinYangMap: Record<string, boolean> = {
    '甲': true, '乙': false,
    '丙': true, '丁': false,
    '戊': true, '己': false,
    '庚': true, '辛': false,
    '壬': true, '癸': false,
  };
  
  const dayIsYang = ganYinYangMap[dayGan] ?? true;
  const comparisonIsYang = ganYinYangMap[comparisonGan] ?? true;
  
  // Same stem = 比肩
  if (dayGan === comparisonGan) {
    return '比肩';
  }
  
  // Same element, different polarity = 劫财
  if (getElementStem(dayGan) === getElementStem(comparisonGan) && dayIsYang !== comparisonIsYang) {
    return '劫财';
  }
  
  // Get relationship
  const dayElement = getElementStem(dayGan);
  const comparisonElement = getElementStem(comparisonGan);
  const relationship = getElementalRelationship(dayElement as WuXing, comparisonElement as WuXing);
  
  // Map to Shi Shen based on relationship and polarity
  if (relationship === '生') return '食神';
  if (relationship === '克') return '伤官';
  if (relationship === '被生') return '正印';
  if (relationship === '制') {
    return dayIsYang !== comparisonIsYang ? '偏官' : '正官';
  }
  
  return '比肩';
}

/**
 * Gets element (Wu Xing) for a Gan stem
 */
function getElementStem(gan: string): string {
  const mapping: Record<string, string> = {
    '甲': '木', '乙': '木',
    '丙': '火', '丁': '火',
    '戊': '土', '己': '土',
    '庚': '金', '辛': '金',
    '壬': '水', '癸': '水',
  };
  return mapping[gan] || '木';
}

/**
 * Calculates complete Ten Gods for all four pillars
 * relative to day master Gan
 * Includes gender-based adjustments for traditional Bazi interpretation
 */
export function calculateShiShenSet(
  dayGan: string,
  yearGan: string,
  monthGan: string,
  hourGan: string,
  gender: 'male' | 'female'
): Record<string, string> {
  const ganYinYangMap: Record<string, boolean> = {
    '甲': true, '乙': false,
    '丙': true, '丁': false,
    '戊': true, '己': false,
    '庚': true, '辛': false,
    '壬': true, '癸': false,
  };

  const dayIsYang = ganYinYangMap[dayGan] ?? true;

  const baseRelationships = {
    yearShen: mapRelationshipToShiShen(dayGan, yearGan, dayIsYang),
    monthShen: mapRelationshipToShiShen(dayGan, monthGan, dayIsYang),
    dayShen: '日干', // Day master itself
    hourShen: mapRelationshipToShiShen(dayGan, hourGan, dayIsYang),
  };

  // Apply gender-based adjustments for traditional interpretation
  return applyGenderAdjustments(baseRelationships, gender);
}

/**
 * Applies gender-based adjustments to Shi Shen relationships
 * Traditional Bazi considers different interpretations for males and females
 */
function applyGenderAdjustments(
  relationships: Record<string, string>,
  gender: 'male' | 'female'
): Record<string, string> {
  const adjustments: Record<string, Record<string, string>> = {
    male: {
      // For males: Standard relationships
      '比肩': '比肩',
      '劫财': '劫财',
      '食神': '食神',
      '伤官': '伤官',
      '正财': '正财',
      '偏财': '偏财',
      '正官': '正官',
      '偏官': '七杀', // Males see 偏官 as more aggressive
      '正印': '正印',
      '偏印': '偏印',
    },
    female: {
      // For females: Some relationships interpreted differently
      '比肩': '比肩',
      '劫财': '姐妹', // Female interpretation of same element opposite polarity
      '食神': '食神',
      '伤官': '伤官',
      '正财': '正财',
      '偏财': '偏财',
      '正官': '正官',
      '偏官': '七杀',
      '正印': '正印',
      '偏印': '偏印',
    }
  };

  const genderAdjustments = adjustments[gender];
  if (!genderAdjustments) {
    return {
      yearShen: relationships.yearShen,
      monthShen: relationships.monthShen,
      dayShen: relationships.dayShen,
      hourShen: relationships.hourShen,
    };
  }

  return {
    yearShen: genderAdjustments[relationships.yearShen] ?? relationships.yearShen,
    monthShen: genderAdjustments[relationships.monthShen] ?? relationships.monthShen,
    dayShen: relationships.dayShen,
    hourShen: genderAdjustments[relationships.hourShen] ?? relationships.hourShen,
  };
}
